#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

WORKING_DIR=/tmp/os-hardening
VERSION=3.2.0

mkdir -p "${WORKING_DIR}"

curl -L -o "${WORKING_DIR}/ansible-os-hardening-${VERSION}.tar.gz" "https://github.com/dev-sec/ansible-os-hardening/archive/${VERSION}.tar.gz"
tar xzf ${WORKING_DIR}/ansible-os-hardening-${VERSION}.tar.gz -C ${WORKING_DIR}
cd ${WORKING_DIR}

cat << EOF > pnda.yml
---
- name: Harden PNDA base image
  hosts: localhost
  roles:
    - ansible-os-hardening
  vars:
    - os_auth_pw_max_age: 99999
EOF

ln -sf ${WORKING_DIR}/ansible-os-hardening-${VERSION} ${WORKING_DIR}/ansible-os-hardening

ansible-playbook -i "localhost," -c local pnda.yml

rm -rf "${WORKING_DIR}"

# XXX Remove ansible
